[package]
name = "git2-binary-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.git2]
version = "0.18.1"
default-features = false
features = ["vendored-libgit2"]
